#ifndef PDBOT_CONFIG_H_
#define PDBOT_CONFIG_H_
#pragma once

#include <cstdlib>
#include <string>

#define ENVIROMENT_VARIABLE_READ_AND_STORE_WITH_PREFIX(prefix, var) \
  const auto var = std::getenv(prefix #var);

#define ENVIROMENT_VARIABLE_READ_AND_STORE(var) \
  ENVIROMENT_VARIABLE_READ_AND_STORE_WITH_PREFIX("PDBOT_", var)

ENVIROMENT_VARIABLE_READ_AND_STORE(DOMAIN);
ENVIROMENT_VARIABLE_READ_AND_STORE(TOKEN);
ENVIROMENT_VARIABLE_READ_AND_STORE(PORT);
ENVIROMENT_VARIABLE_READ_AND_STORE(HOST);
ENVIROMENT_VARIABLE_READ_AND_STORE(PUBLIC_KEY_PATH);
ENVIROMENT_VARIABLE_READ_AND_STORE(PRIVATE_KEY_PATH);
ENVIROMENT_VARIABLE_READ_AND_STORE(USER_ID_STRINGED);
const auto USER_ID = std::stoll(USER_ID_STRINGED);

#undef ENVIROMENT_VARIABLE_READ_AND_STORE
#undef ENVIROMENT_VARIABLE_READ_AND_STORE_WITH_PREFIX

#endif  // PDBOT_CONFIG_H_
