set(REQUIRED_CXX_COMPILER "Clang")

if (NOT "${CMAKE_CXX_COMPILER_ID}" STREQUAL REQUIRED_CXX_COMPILER)
  message(FATAL_ERROR "Compiler ${REQUIRED_CXX_COMPILER} required. ${CMAKE_CXX_COMPILER_ID} found")
endif()
